```{r echo = FALSE}
knitr::opts_chunk$set(out.width = "100%")
```

# Programming Platforms

These sections provide a general overview of how to use RStudio on AnVIL.

<br>

## Video overview on using RStudio

```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/_child_rstudio_video.Rmd",
  repo_name = "jhudsl/AnVIL_Template"
)
```

## Launching RStudio

:::: {.borrowed_chunk}
```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/_child_rstudio_launch.Rmd",
  repo_name = "jhudsl/AnVIL_Template"
)
```
::::

## Touring RStudio

:::: {.borrowed_chunk}
```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/_child_rstudio_tour.Rmd",
  repo_name = "jhudsl/AnVIL_Template"
)
```
::::

## Pausing RStudio

:::: {.borrowed_chunk}
```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/_child_rstudio_pause.Rmd",
  repo_name = "jhudsl/AnVIL_Template"
)
```
::::

## Deleting RStudio

:::: {.borrowed_chunk}
```{r, echo = FALSE, results='asis'}
cow::borrow_chapter(
  doc_path = "child/_child_rstudio_delete.Rmd",
  repo_name = "jhudsl/AnVIL_Template"
)
```
::::
